apiVersion: apps/v1
kind: Deployment
metadata:
  name: nf-ui

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nf-ui
  template:
    metadata:
      labels:
        app: nf-ui
    spec:
      containers:
        - name: nf-ui-node
          image: movsesyan/nf-ui
